default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: TaskManagement_development

production:
  adapter: postgresql
  encoding: unicode